name: JavaLatest

on: [ push ]
      
jobs:
  javaLatest:
    # internal comment counter: 100
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-latest, windows-2019]
        update: [x]
      fail-fast: false
      max-parallel: 5
    name: JDK ${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: maxim-lobanov/setup-java@v2-preview
      with:
        java-version: ${{ matrix.update }}
        distribution: zulu
    - name: java -version
      run: java -version
