name: Java11

on: [ push ]
jobs:
  java11:
    # internal comment counter: 100
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-latest, windows-2019]
        distribution: ['adopt-hotspot', 'adopt-openj9']
        update: [x, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
        package: [jdk, jre]
        exclude:
          - {package: jre, update: 1}
          - {package: jre, update: 2}
      fail-fast: false
      max-parallel: 5
    name: ${{ matrix.package }} 11.0.${{ matrix.update }}, ${{ matrix.os }} ${{ matrix.distribution }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v2.1.0
      with:
        java-package: ${{ matrix.package }}
        java-version: 11.0.${{ matrix.update }}
        distribution: ${{ matrix.distribution }}
    - name: java -version
      run: java -version
