name: Java9

on: [ push ]

jobs:
  java9:
    # internal comment counter: 100
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-latest, windows-2019]
        update: [x, 7, 4, 1, 0]
      fail-fast: false
      max-parallel: 4
    name: JDK 9.0.${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@implement-v2-tests
      with:
        java-version: 9.0.${{ matrix.update }}
        distribution: zulu
    - name: java -version
      run: java -version
