name: Java12

on: [ push ]

jobs:
  java12:
    # internal comment counter: 100
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-latest, windows-2019]
        update: [x, 2, 1, 0]
      fail-fast: false
      max-parallel: 5
    name: JDK 12.0.${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v2.1.0
      with:
        java-version: 12.0.${{ matrix.update }}
        distribution: zulu
    - name: java -version
      run: java -version
