name: Java16

on: [ push ]
      
jobs:
  java16:
    # internal comment counter: 103
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-latest, windows-2019]
        update: [16.0.0-ea, 16.0.0-ea.5, 16-ea]
      fail-fast: false
      max-parallel: 6
    name: JDK ${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v2.1.0
      with:
        java-version: ${{ matrix.update }}
        distribution: zulu
    - name: java -version
      run: java -version
