name: Java13

on: [ push ]
      
jobs:
  java13:
    # internal comment counter: 100
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-latest, windows-2019]
        update: [x, 6, 5, 4, 3, 2, 1, 0]
        package: [jdk, jre]
        exclude:
          - {update: 0, package: jre}
      fail-fast: false
      max-parallel: 6
    name: ${{ matrix.package }} 13.0.${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up ${{ matrix.package }}
      uses: actions/setup-java@implement-v2-tests
      with:
        java-package: ${{ matrix.package }}
        java-version: 13.0.${{ matrix.update }}
        distribution: zulu
    - name: java -version
      run: java -version
