name: Java7

on: [ push ]

jobs:
  java7:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019]
        update: [x, 292, 282, 272, 262, 252, 242, 232, 222, 211, 201, 191, 181, 171, 161, 154, 141, 131, 121, 111, 101, 95]
      fail-fast: false
      max-parallel: 5
    name: JDK 7.0.${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@implement-v2-tests
      with:
        java-version: 7.0.${{ matrix.update }}
        distribution: zulu
    - name: java -version
      run: java -version

  java7-mac:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
        update: [x, 292, 282, 272, 262, 252, 242, 232, 222, 211, 201, 191, 181, 171, 161, 154, 141, 131, 121, 111, 101, 95, 91, 85, 80, 79, 76, 72, 65, 60, 55]
      fail-fast: false
      max-parallel: 5
    name: Mac-JDK 7.0.${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@implement-v2-tests
      with:
        java-version: 7.0.${{ matrix.update }}
        distribution: zulu
    - name: java -version
      run: java -version
