name: Latest_JDK_Updates

on: [ push ]

jobs:
  java:
    # internal comment counter: 103
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-latest, windows-2019]
        version: [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, x]
        exclude:
          - os: macOS-latest
            version: 6
      fail-fast: false
      max-parallel: 7
    name: JDK ${{ matrix.version }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: maxim-lobanov/setup-java@v2-preview
      with:
        java-version: ${{ matrix.version }}
        distribution: zulu
    - name: java -version
      run: java -version
