name: Zing_Latest_JDK

on:
  push:
    paths:
      - '.github/workflows/zingJdkTest.yml'

jobs:
  jdk:
    # internal comment counter: 103
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        version: [7, 8, 11]
      fail-fast: false
      max-parallel: 6
    name: JDK ${{ matrix.version }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: zing-actions/setup-java@implement-v2-tests
      with:
        java-version: ${{ matrix.version }}
        distribution: zulu
    - name: java -version
      run: java -version
      
#  jre:
#    # internal comment counter: 103
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os: [ubuntu-18.04]
#        version: [7, 8]
#      fail-fast: false
#      max-parallel: 7
#    name: JRE ${{ matrix.version }}, ${{ matrix.os }}
#
#    steps:
#    - uses: actions/checkout@v1
#    - name: Set up JRE
#      uses: zing-actions/setup-java@v1
#      with:
#        java-version: ${{ matrix.version }}
#        java-package: jre 
#    - name: java -version
#      run: java -version
